### ISSUE TITLE
The style in light mode

### ISSUE THREAD

**Issue by JinIgarashi** [UNDP-Data/geohub#88]
This commit (https://github.com/UNDP-Data/geohub/commit/03c05672c13190d7d1e9dcb7a41785da477f1063) affected all color styling when it is the light color mode.

```css
        @media (prefers-color-scheme: dark) {
          background: #323234;
          border-color: #30363d;
          color: white;
        }
```

- dark mode
![image](https://user-images.githubusercontent.com/2639701/160922642-a4f0c81f-91b6-402e-bb01-d629657c84a2.png)

It works fine in dark mode

- light mode
![image](https://user-images.githubusercontent.com/2639701/160922676-a5d0a228-1ff8-44a2-b6a6-3c38f1d76363.png)

Everything became white color, invisible.
